$schema: http://json-schema.org/schema#

type: array
items:
  type: object
  additionalProperties: false
  required:
    - pid
    - products
  properties:
    pid:
      type: string
      format: int64
    products:
      type: array
      items:
        type: object
        additionalProperties: false
        required:
          - productId
          - productName
        properties:
          productId:
            type: string
          productName:
            type: string
          productLang:
            title: Language tag (RFC 3066)
            type: string
