logging:
  version: 1
  root:
    handlers:
      - default
    level: DEBUG
  handlers:
    default:
      class: logging.StreamHandler
      formatter: default
  formatters:
    default:
      format: '%(asctime)s %(name)s %(levelname)s %(message)s'

service:
  journey:
    route_url: "https://api.ul.se/api/v3/line/"
    period: 30
    buss_id_url: "http://who.am.i"
    input:
      service:
        format: json
    output:      
      - route
      - mqtt_journey
  mqtt:
    server: mqtt://127.0.0.1/
    #config:      
    input:
      service:
        topic: /service/v1/feeder/service
        format: json                              
    output:
      mqtt_journey:
        topic: /service/v1/journey
        format: json
      mqtt_last_stop:
        topic: /service/v1/lastStop
        format: json
      mqtt_next_stop:
        topic: /service/v1/nextStop
        format: json
      mqtt_gps:
        topic: /service/v1/gps/rmc
        format: nmea_string
      mqtt_time:
        topic: /service/v1/Validate/time
        format: json
  gps:
    driver: bobcat_feeder.gps.router:Listner
    #driver: bobcat_feeder.gps.file:Listner
    driver_config:
      server: "192.168.1.3"    
      port: 10110
      tcp: False
    output:
      - mqtt_gps
      - mqtt_time
    period: 5

        